[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.20"
# EVM version must be Paris not Shanghai to prevent PUSH0 incompatibility with other EVM L1s
evm_version = "paris"
optimizer_runs = 1000000
# viaIR = true

[fmt]
line_length = 160

[fuzz]
# runs = 250000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[invariant]
runs = 1000
depth = 25
fail_on_revert = true
dictionary_weight = 80
include_storage = true
include_push_bytes = true
