name: Slither Report
on: [push, pull_request]
jobs:
  slither-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: forge install

      - name: Forge clean
        run: forge clean

      - name: Forge build without test & script
        run: forge build --build-info --skip test --skip script
      - uses: crytic/slither-action@v0.3.0
        with:
          slither-args: "--compile-force-framework 'foundry' --foundry-out-directory 'out' --ignore-compile --skip-clean --filter-paths '(seaport|openzeppelin)' --checklist"
          fail-on: "low"